version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=deepobserver
      - POSTGRES_PASSWORD=deepobserver
      - POSTGRES_DB=deepobserver
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: